START TRANSACTION ; -- INDICAMOS QUE SE COMIENZA UNA TRANSACCION
	DELETE FROM NOTAS_ALUMNOS WHERE COD_ALUMNO > 4;
	INSERT INTO ALUMNOS VALUES(990, 'xxxxxx','xxxxxx', 'xxxxx@gmail.com',20,2);
	INSERT INTO NOTAS_ALUMNOS VALUES(990, 2, 1,0);
COMMIT; -- INDICA EL FINAL DE LA TRANSACCION


SELECT * FROM NOTAS_ALUMNOS;

ROLLBACK; -- SI DESPUES DE UN COMMIT, HAGO UN ROLLBACK, NO SE DESHACE ABSOLUTAMENTE NADA