-- AUTOCOMMIT - TRANSACCIONES
SHOW VARIABLES LIKE 'autocommit';
SET AUTOCOMMIT = 0; 
SHOW ENGINES;

SET AUTOCOMMIT = 1; 

USE ACADEMIA;
SELECT * FROM ALUMNOS;


DELETE FROM NOTAS_ALUMNOS WHERE COD_ALUMNO = 1;
DELETE FROM ALUMNOS WHERE COD_ALUMNO = 1;
ROLLBACK;

SELECT * FROM NOTAS_ALUMNOS;
DELETE FROM NOTAS_ALUMNOS WHERE COD_ALUMNO = 3;
ROLLBACK;

DELETE FROM NOTAS_ALUMNOS WHERE COD_ALUMNO > 4;
INSERT INTO ALUMNOS VALUES(990, 'xxxxxx','xxxxxx', 'xxxxx@gmail.com',20,2);
INSERT INTO NOTAS_ALUMNOS VALUES(990, 2, 1,0);
Rollback;


