/** 

INFORMATION_SCHEMA  


**/

show databases;

use information_schema;
show tables;

desc information_schema.tables;

SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA="world" AND table_name="country";

select * from information_Schema.table_constraints where table_Schema="RESTRICCIONES" AND table_name="PEDIDOS";

USE RESTRICCIONES;
CREATE TABLE EJEMPLO (
CODIGO INT PRIMARY KEY,
PROVINCIA VARCHAR(50),
FECHA DATE,
FECHA_PAGO DATE,
NOMBRE VARCHAR(100) CONSTRAINT CHECK_NOMBRE CHECK(LENGTH(NOMBRE)>2),
CONSTRAINT CHECK_FECHAS CHECK(FECHA_PAGO>FECHA)
);



DESC EJEMPLO;
SHOW CREATE TABLE EJEMPLO;

/*
CREATE TABLE `EJEMPLO` (
  `CODIGO` int NOT NULL,
  `PROVINCIA` varchar(50) DEFAULT NULL,
  `FECHA` date DEFAULT NULL,
  `FECHA_PAGO` date DEFAULT NULL,
  `NOMBRE` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`CODIGO`),
  CONSTRAINT `CHECK_FECHAS` CHECK ((`FECHA_PAGO` > `FECHA`)),
  CONSTRAINT `CHECK_NOMBRE` CHECK ((length(`NOMBRE`) > 2))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

*/

SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME = "EJEMPLO" AND TABLE_SCHEMA="RESTRICCIONES";

/*
NO se pueden modificar restricciones ya creadas. Pero sí podemos borrar la restricción y después 
añadir una restricción nueva

Añadir una restriccion -> ALTER TABLE TABLA ADD CONSTRAINT

Borrar una restricción -> ALTER TABLE TABLA DROP CONSTRAINT
*/

SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME = "EJEMPLO" AND TABLE_SCHEMA="RESTRICCIONES";

DROP TABLE EJEMPLO;

CREATE TABLE EJEMPLO (
CODIGO INT,
PROVINCIA VARCHAR(50),
FECHA DATE,
FECHA_PAGO DATE,
NOMBRE VARCHAR(100)
);

ALTER TABLE EJEMPLO ADD CONSTRAINT CLAVE PRIMARY KEY(CODIGO);
ALTER TABLE EJEMPLO ADD CONSTRAINT CHECK1 CHECK (LENGTH(NOMBRE)>2);
ALTER TABLE EJEMPLO ADD CONSTRAINT CHECK2 CHECK (FECHA_PAGO>FECHA);

DESC EJEMPLO;


-- not null y default
ALTER TABLE EJEMPLO MODIFY PROVINCIA VARCHAR(50) NOT NULL;
ALTER TABLE EJEMPLO MODIFY PROVINCIA VARCHAR(50) NULL;

ALTER TABLE EJEMPLO ALTER PROVINCIA SET DEFAULT "CACERES";

ALTER TABLE EJEMPLO DROP CONSTRAINT CHECK2; -- HAY QUE TENER LA PRECAUCIÓN DE PONERLE UN NOMBRE A LAS RESTRICCIONES 
ALTER TABLE CLIENTES DROP PRIMARY KEY; -- NO PODEMOS BORRAR UNA PRIMARY KEY DE LA QUE DEPENDA UNA FOREIGN KEY






