-- CONSTRAINTS (RESTRICCIONES)
/*
- Sirven para poner reglas dentro de los datos que vamos a guardar en una tabla
- Guardar la integridad de la información
- Existen restricciones a nivel de tabla y a nivel de columna
*/

CREATE SCHEMA RESTRICCIONES;
USE RESTRICCIONES;

-- **** RESTRICCIONES MÁS HABITUALES ****

-- NOT NULL-> impide tener un valor nulo en un campo
CREATE TABLE TABLA1 (
CODIGO INT NOT NULL,
NOMBRE VARCHAR(50) );

DESC TABLA1;

INSERT INTO TABLA1(codigo) values(10); 
INSERT INTO TABLA1(nombre) values("Juan"); -- sale error porque codigo no puede ser nulo

select * from tabla1;

-- PRIMARY KEY-> impide que haya valores duplicados y tampoco soporta nulos
	-- NATURAL: dni, matricula coche, codigo producto
    -- SUBROGADAS: (claves que me invento yo) Codigo de alumno, codigo departamento
    

CREATE TABLE TABLA2(
CODIGO INT PRIMARY KEY,
NOMBRE VARCHAR(50));

DESC TABLA2;

INSERT INTO TABLA2(CODIGO, NOMBRE) VALUES(1, "juan");
INSERT INTO TABLA2(CODIGO, NOMBRE) VALUES(1, "juan"); -- error, valores duplicados

CREATE TABLE TABLA3 (
COD_ALUMNO INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE_ALUMNO VARCHAR(50) );

DESC TABLA3;

INSERT INTO TABLA3(NOMBRE_ALUMNO) VALUES("ALBERTO");
SELECT * FROM TABLA3;

INSERT INTO TABLA3(NOMBRE_ALUMNO) VALUES("MARIA");

CREATE TABLE TABLA4 (
COD_ALUMNO INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE_ALUMNO VARCHAR(50) );

ALTER TABLE TABLA4 auto_increment = 100;

INSERT INTO TABLA4(NOMBRE_ALUMNO) VALUES("ALBERTO");
INSERT INTO TABLA4(NOMBRE_ALUMNO) VALUES("SOFIA");
INSERT INTO TABLA4(NOMBRE_ALUMNO) VALUES("JUAN");

SELECT * FROM TABLA4;

-- *** constraints a nivel de tabla

CREATE TABLE TABLA5 (
CODIGO INT,
PRODUCTO VARCHAR(50),
PRIMARY KEY (CODIGO));

DESC TABLA5;

DROP TABLE TABLA5;

CREATE TABLE TABLA5 (
CODIGO INT,
COD_PROVEEDOR INT,
PRODUCTO VARCHAR(50),
PRIMARY KEY (CODIGO, COD_PROVEEDOR)); -- a nivel de tabla, ahora tenemos una clave primaria con dos campos de la tabla

INSERT INTO TABLA5 (CODIGO, COD_PROVEEDOR, PRODUCTO) VALUES (1, 003, "tijeras");
INSERT INTO TABLA5 (CODIGO, COD_PROVEEDOR, PRODUCTO) VALUES (1, 004, "lapices");
INSERT INTO TABLA5 (CODIGO, COD_PROVEEDOR, PRODUCTO) VALUES (1, 003, "rotulador");

select * from tabla5;

-- UNIQUE -> impide que haya valores duplicados en un campo
CREATE TABLE TABLA6 (
COD_EMPLEADO INT PRIMARY KEY,
DNI VARCHAR(30) UNIQUE, 
NOMBRE VARCHAR(50)
);

INSERT INTO TABLA6 VALUES(1, "123456A", "JUAN");
INSERT INTO TABLA6 VALUES(2, "123456A", "MARIA"); -- NO SE PUEDE REGISTRAR, ENTRADA UNIQUE DUPLICADA
INSERT INTO TABLA6 VALUES(3, "678901J", "MARIO");

SELECT * FROM TABLA6;

INSERT INTO TABLA6 VALUES(2,NULL , "MARIA");
INSERT INTO TABLA6(COD_EMPLEADO, NOMBRE) VALUES(4, "LAURA");

CREATE TABLE TABLA7 (
COD_EMPLEADO INT PRIMARY KEY,
DNI VARCHAR(30), 
NOMBRE VARCHAR(50), 
UNIQUE(DNI, NOMBRE)
);

-- DEFAULT -> permite poner un valor por defecto en una columna
CREATE TABLE ALUMNOS_DEFAULT(
CODIGO INT PRIMARY KEY,
PAIS VARCHAR(50) NOT NULL DEFAULT "ESPAÑA",
FECHA_ALTA DATE NOT NULL DEFAULT(current_date()));

INSERT INTO ALUMNOS_DEFAULT (CODIGO) VALUES (1);
INSERT INTO ALUMNOS_DEFAULT (CODIGO, PAIS) VALUES (2, "Mexico");
INSERT INTO ALUMNOS_DEFAULT (CODIGO, FECHA_ALTA) VALUES (3, "2023-11-01");

SELECT * FROM ALUMNOS_DEFAULT;

-- CHECK -> condicion que ha de cumplirse dentro de una columna
CREATE TABLE CLIENTES_CHECK(
COD_CLIENTE INT PRIMARY KEY,
NOMBRE VARCHAR(50),
EDAD INT, 
FECHA_ALTA DATE NOT NULL DEFAULT(current_date()),
CONSTRAINT CHECK(EDAD>18)
);

INSERT INTO CLIENTES_CHECK VALUES(1, "PACO", 50, "2023-01-01");
INSERT INTO CLIENTES_CHECK VALUES(2, "JUAN", 18, "2023-01-01");
DROP TABLE CLIENTES_CHECK;

CREATE TABLE CLIENTES_CHECK(
COD_CLIENTE INT PRIMARY KEY,
NOMBRE VARCHAR(50),
EDAD INT CHECK(EDAD>18), 
FECHA_ALTA DATE NOT NULL DEFAULT(current_date())
);

INSERT INTO CLIENTES_CHECK VALUES(1, "PACO", 50, "2023-01-01");
INSERT INTO CLIENTES_CHECK VALUES(2, "JUAN", 18, "2023-01-01");

CREATE TABLE COMPRAS_CLIENTES(
COD_CLIENTE INT PRIMARY KEY,
NOMBRE VARCHAR(50),
EDAD INT CHECK(EDAD>18), 
FECHA_COMPRA DATE NOT NULL DEFAULT(current_date()),
FECHA_PAGO DATE, CONSTRAINT CHECK(FECHA_PAGO > FECHA_COMPRA)
);


INSERT INTO COMPRAS_CLIENTES VALUES (1, "PACO", 40, "2024-3-05", current_date());
INSERT INTO COMPRAS_CLIENTES VALUES (2, "LUCIA", 40, "2024-03-05", "2024-03-01");


-- FOREING KEY -> relaciona unas tablas con otras para que no se rompa la integridad entre ellas


