SELECT * FROM VISTA;
INSERT INTO VISTA VALUES (23, 'XXXXX');
INSERT INTO VISTA VALUES (43, 'YYYY');
CREATE OR REPLACE VIEW VISTA_CHECK AS SELECT * FROM TABLA_VISTA WHERE CODIGO > 4;
SELECT * FROM VISTA_CHECK;
SELECT * FROM TABLA_VISTA;

INSERT INTO VISTA_CHECK VALUES (3, 'VISTA');

-- CHECK OPTION
CREATE OR REPLACE VIEW VISTA_CHECK AS
SELECT * FROM TABLA_VISTA WHERE CODIGO > 4
WITH CHECK OPTION;

INSERT INTO VISTA_CHECK VALUES (67, 'VISTA2');


-- RENOMBRADO Y EL BORRADO DE VISTAS
RENAME TABLE VISTA TO VISTA_NUEVA;

SELECT * FROM VISTA_NUEVA;

DROP VIEW IF EXISTS VISTA_NUEVA;








