-- SUBCONSULTAS EN 'SELECT'

-- EJEMPLO SIMPLE 
Use world;

SELECT name, continent, region, (SELECT NOW()) FROM COUNTRY;

SELECT Name, population, (SELECT SUM(POPULATION) FROM COUNTRY) AS "POBLACION_MUNDIAL_TOTAL", 
(POPULATION*100/(SELECT SUM(POPULATION) FROM COUNTRY)) AS "PORCENTAJE_POBLACION" FROM COUNTRY;


-- REFERENCIANDO A LA CONSULTA PRINCIPAL 
SELECT CODE, NAME, (SELECT COUNT(*) FROM CITY WHERE COUNTRYCODE = PAISES.CODE) FROM COUNTRY AS PAISES;

-- SUBCONSULTAS EN 'FROM'
 
SELECT * FROM (SELECT NAME, CONTINENT, POPULATION FROM COUNTRY) AS TABLA;

SELECT CONTINENT, TOTAL_POPULATION FROM 
	(SELECT CONTINENT, SUM(POPULATION) AS TOTAL_POPULATION FROM COUNTRY GROUP BY CONTINENT) AS POBLACION;

SELECT NAME, POPULATION AS 'POBLACION_PAIS', TOTAL_POBLACION 
FROM (SELECT CODE, CONTINENT, SUM(POPULATION) AS 'TOTAL_POBLACION' FROM COUNTRY GROUP BY CODE, CONTINENT) AS T1 
INNER JOIN city ON COUNTRYCODE = CODE;

-- SUBCONSULTAS EN 'WHERE'
SELECT NAME, POPULATION FROM COUNTRY WHERE POPULATION = (SELECT MAX(POPULATION) FROM COUNTRY);

SELECT NAME, POPULATION FROM COUNTRY WHERE POPULATION > (SELECT AVG(POPULATION) FROM COUNTRY);











