-- Crear tablas
USE DML;

CREATE TABLE PROVEEDORES (
COD_PROV INT,
NOMBRE VARCHAR(45), 
DIRECCION VARCHAR(100),
FECHA_ALTA DATE) ;

DESC PROVEEDORES;

CREATE TABLE IF NOT EXISTS PROVEEDORES (
COD_PROV INT,
NOMBRE VARCHAR(45), 
DIRECCION VARCHAR(100),
FECHA_ALTA DATE) ;

/* Modificar tablas-> añadir columnas, modificar columnas, borrar y renombrar columnas

 ALTER TABLE -- Permite añadir nuevas columnas, modificar las existentes, borrarlas y añadir restricciones (constraints)

- añadir columna nueva
ALTER TABLE TABLA ADD columna tipo;
ALTER TABLE TABLA ADD columna tipo AFTER columnaTabla;
ALTER TABLE TABLA ADD columna tipo FIRST;

-- Borrar columna
ALTER TABLE TABLA DROP columna;

-- Modificar columa existente
ALTER TABLE TABLA MODIFY columa tipo;
ALTER TABLE TABLA CHANGE COLUMN nombre_antiguo nombre_nuevo tipo AFTER columna;
*/
DESC PROVEEDORES;

ALTER TABLE PROVEEDORES ADD FECHA_MODIFICACION DATE;
ALTER TABLE PROVEEDORES ADD COD_PRODUCTO INT AFTER COD_PROV;
ALTER TABLE PROVEEDORES ADD FECHA_COMPRA DATE FIRST;
ALTER TABLE PROVEEDORES ADD TELEFONO INT;

ALTER TABLE PROVEEDORES DROP FECHA_MODIFICACION;

ALTER TABLE PROVEEDORES MODIFY FECHA_ALTA TIMESTAMP;
ALTER TABLE PROVEEDORES MODIFY TELEFONO  INT AFTER DIRECCION, 
						MODIFY FECHA_COMPRA DATE AFTER FECHA_ALTA;

INSERT INTO PROVEEDORES VALUES ('2024-01-01', 1, 1, 'Proveedor1', 'Direccion 1', now());
SELECT * FROM PROVEEDORES;

ALTER TABLE PROVEEDORES MODIFY DIRECCION DECIMAL;

ALTER TABLE PROVEEDORES CHANGE COLUMN COD_PROV COD_PROVEEDOR INT FIRST;

-- Columnas autogeneradas 

CREATE TABLE CLIENTES (
CODIGO_CLIENTE INT, 
NOMBRE VARCHAR(30),
APELLIDO1 VARCHAR(30), 
APELLIDO2 VARCHAR(30),
NOMBRE_COMPLETO VARCHAR(100) generated always AS (CONCAT(NOMBRE, ' ', APELLIDO1, ' ', APELLIDO2, ' ')));

DESC CLIENTES;

INSERT INTO CLIENTES (CODIGO_CLIENTE, NOMBRE, APELLIDO1, APELLIDO2) VALUES (1, 'Juan', 'López', 'García');

SELECT * FROM CLIENTES;

-- Renombrar y mover tablas
-- RENAME TABLE nombre_antiguo TO nombre_nuevo;

RENAME TABLE PROVEEDORES TO PROVEEDOR;
DESC PROVEEDOR;

RENAME TABLE CLIENTES TO CLIENTE;

RENAME TABLE PROVEEDOR TO OP_CONJUNTOS.PROVEEDOR;


-- Borrar tablas
-- DROP TABLE TABLA
-- DROP TABLE IF EXISTS TABLA
-- DROP TABLE IF EXISTS TABLA CASCADE; (BORRA TABLA PADRE Y TABLA/S HIJO)

DROP TABLE CLIENTE;
DESC CLIENTE;
















