/*
			 OLD      NEW
INSERT ---->  -        X
UPDATE----->  X        X
DELETE ---->  X        -

NEW.campo
OLD.campo

*/
DELIMITER //

DROP TRIGGER IF EXISTS update_cursos//

CREATE TRIGGER update_cursos BEFORE UPDATE ON CURSOS FOR EACH ROW
precedes update_cursos2
BEGIN
	IF NEW.precio < 100 THEN
		set NEW.precio = 100;
    END IF;
    
	INSERT INTO AUDIT(TABLA, OPERACION, USUARIO) VALUES ('CURSOS', 'UPDATE', current_user());
END //

UPDATE CURSOS SET PRECIO = 10 WHERE COD_CURSO=3//
UPDATE CURSOS SET PRECIO = 10 WHERE COD_CURSO=6//

SELECT * FROM CURSOS//


DROP TRIGGER IF EXISTS update_cursos2//

CREATE TRIGGER update_cursos2 BEFORE UPDATE ON CURSOS FOR EACH ROW

BEGIN
	INSERT INTO AUDIT(TABLA, OPERACION, USUARIO) VALUES ('CURSOS', 'UPDATE 2', current_user());
END //


UPDATE CURSOS SET PRECIO = 900 WHERE COD_CURSO=5//
UPDATE CURSOS SET PRECIO = 700 WHERE COD_CURSO=6//

SELECT * FROM AUDIT;





