/*
SIGNAL 45000 -> PERMITE PARAR EL PROCESO DE UN TRIGGER
 */
 
DELIMITER //
 
CREATE TRIGGER delete_cursos BEFORE DELETE ON CURSOS FOR EACH ROW
BEGIN
    IF current_USER() <> 'PEPE@%' then
		signal sqlstate '45000'; 
	END IF;
	INSERT INTO AUDIT(TABLA, OPERACION, USUARIO) VALUES ('CURSOS', 'DELETE', current_user());
END //


SELECT * FROM CURSOS//

DELETE FROM CURSOS WHERE COD_CURSO = 555//